import { Dimensions } from 'react-native';
const screenHeight = Dimensions.get('window').height;
const screenWidth = Dimensions.get('window').width;

export const phonesLib = [
  {
    phoneName: 'iPhone 12 mini',
    sizesTwo: 62,
    sizesThree: 115,
    sizesFour: screenHeight - 96,
    left: screenWidth / 2 - 32.5,
  },
  {
    phoneName: 'iPhone 12',
    sizesTwo: 60,
    sizesThree: 113,
    sizesFour: screenHeight - 98,
    left: screenWidth / 2 - 32.5,
  },
  {
    phoneName: 'iPhone 12 Pro',
    sizesTwo: 60,
    sizesThree: 113,
    sizesFour: screenHeight - 98,
    left: screenWidth / 2 - 32.5,
  },
  {
    phoneName: 'iPhone 12 Pro Max',
    sizesTwo: 60,
    sizesThree: 113,
    sizesFour: screenHeight - 98,
    left: screenWidth / 2 - 32.5,
  },
  {
    phoneName: 'iPhone 11',
    sizesTwo: 62,
    sizesThree: 114,
    sizesFour: screenHeight - 85,
    left: screenWidth / 2 - 32.5,
  },
  {
    phoneName: 'iPhone 11 Pro',
    sizesTwo: 57,
    sizesThree: 110,
    sizesFour: screenHeight - 84,
    left: screenWidth / 2 - 32.5,
  },
  {
    phoneName: 'iPhone 11 Pro Max',
    sizesTwo: 58,
    sizesThree: 110,
    sizesFour: screenHeight - 85,
    left: screenWidth / 2 - 32.5,
  },
  {
    phoneName: 'iPhone X',
    sizesTwo: 58,
    sizesThree: 110,
    sizesFour: screenHeight - 83,
    left: screenWidth / 2 - 32.5,
  },
  {
    phoneName: 'iPhone XS',
    sizesTwo: 58,
    sizesThree: 110,
    sizesFour: screenHeight - 83,
    left: screenWidth / 2 - 32.5,
  },
  {
    phoneName: 'iPhone XS Max',
    sizesTwo: 58,
    sizesThree: 110,
    sizesFour: screenHeight - 83,
    left: screenWidth / 2 - 32.5,
  },
  {
    phoneName: 'iPhone SE',
    sizesTwo: 32,
    sizesThree: 85,
    sizesFour: screenHeight - 70,
    left: screenWidth / 2 - 32.5,
  },
  {
    phoneName: 'iPhone XR',
    sizesTwo: 62,
    sizesThree: 114,
    sizesFour: screenHeight - 85,
    left: screenWidth / 2 - 32.5,
  },
  {
    phoneName: 'iPhone 8',
    sizesTwo: 32,
    sizesThree: 85,
    sizesFour: screenHeight - 70,
    left: screenWidth / 2 - 32.5,
  },
  {
    phoneName: 'iPhone 8 Plus',
    sizesTwo: 32,
    sizesThree: 85,
    sizesFour: screenHeight - 70,
    left: screenWidth / 2 - 32.5,
  },
  {
    phoneName: 'iPhone 7',
    sizesTwo: 32,
    sizesThree: 86,
    sizesFour: screenHeight - 70,
    left: screenWidth / 2 - 32.5,
  },
  {
    phoneName: 'iPhone 7 Plus',
    sizesTwo: 32,
    sizesThree: 86,
    sizesFour: screenHeight - 70,
    left: screenWidth / 2 - 32.5,
  },
  {
    phoneName: 'iPhone 6',
    sizesTwo: 32,
    sizesThree: 86,
    sizesFour: screenHeight - 70,
    left: screenWidth / 2 - 32.5,
  },
  {
    phoneName: 'iPhone 6s',
    sizesTwo: 32,
    sizesThree: 85,
    sizesFour: screenHeight - 70,
    left: screenWidth / 2 - 32.5,
  },
  {
    phoneName: 'iPhone 6s plus',
    sizesTwo: 32,
    sizesThree: 86,
    sizesFour: screenHeight - 70,
    left: screenWidth / 2 - 32.5,
  },
  {
    phoneName: 'iPhone 5s',
    sizesTwo: 32,
    sizesThree: 86,
    sizesFour: screenHeight - 70,
    left: screenWidth / 2 - 32.5,
  },
];
